# Задача регрессии для CC50
В этом разделе мы будем предсказывать показатель цитотоксичности CC50, используя аналогичный подход: логарифмирование целевой переменной (pCC50) и оптимизацию гиперпараметров.

In [ ]:
from sklearn.metrics import root_mean_squared_error
from sklearn.metrics import mean_squared_error
import lightgbm as lgb
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.metrics import mean_squared_error, r2_score
import xgboost as xgb
import seaborn as sns
import lightgbm as lgb

In [ ]:


# Load the dataset
file_path = '/content/cleaned_molecular_data.csv'
df = pd.read_csv(file_path)

# Display basic information
print("Dataset Shape:", df.shape)
display(df.head())
print(df.info())

Dataset Shape: (966, 214)

,"IC50, mM","CC50, mM",SI,MaxAbsEStateIndex,MaxEStateIndex,MinAbsEStateIndex,MinEStateIndex,qed,SPS,MolWt,...,fr_sulfonamd,fr_sulfone,fr_term_acetylene,fr_tetrazole,fr_thiazole,fr_thiocyan,fr_thiophene,fr_unbrch_alkane,fr_urea,is_outlier
0,6.239374,175.482382,28.125000,5.094096,5.094096,0.387225,0.387225,0.417362,42.928571,384.652,...,0,0,0,0,0,0,0,3,0,1
1,0.771831,5.402819,7.000000,3.961417,3.961417,0.533868,0.533868,0.462473,45.214286,388.684,...,0,0,0,0,0,0,0,3,0,1
2,223.808778,161.142320,0.720000,2.627117,2.627117,0.543231,0.543231,0.260923,42.187500,446.808,...,0,0,0,0,0,0,0,3,0,1
3,1.705624,107.855654,63.235294,5.097360,5.097360,0.390603,0.390603,0.377846,41.862069,398.679,...,0,0,0,0,0,0,0,4,0,1
4,107.131532,139.270991,1.300000,5.150510,5.150510,0.270476,0.270476,0.429038,36.514286,466.713,...,0,0,0,0,0,0,0,0,0,1

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 966 entries, 0 to 965
Columns: 214 entries, IC50, mM to is_outlier
dtypes: float64(107), int64(107)
memory usage: 1.6 MB
None

In [ ]:
# 1. Подготовка данных для CC50
target_cc50 = 'CC50, mM'
exclude_cols_cc = ['IC50, mM', 'CC50, mM', 'SI', 'IC50_above_median', 'CC50_above_median', 'SI_above_median', 'SI_above_8', 'is_outlier']

# Признаки (numeric)
relevant_features_cc = [col for col in df.select_dtypes(include=[np.number]).columns if col not in exclude_cols_cc]

# Убираем строки, где CC50 может быть NaN или некорректным (если есть)
df_cc = df.dropna(subset=[target_cc50]).copy()

X_cc = df_cc[relevant_features_cc]
y_cc_log = -np.log10(df_cc[target_cc50])

# Разделение на выборки
X_train_cc, X_test_cc, y_train_cc, y_test_cc = train_test_split(X_cc, y_cc_log, test_size=0.2, random_state=42)

print(f"Samples for CC50 task: {len(df_cc)}")
print(f"Target distribution (pCC50) mean: {y_cc_log.mean():.2f}")

Samples for CC50 task: 966
Target distribution (pCC50) mean: -2.41

### Базовые модели (стандартные параметры) для CC50

In [ ]:
# Определение стандартных моделей для baseline
standard_models = {
    "GBR (Default)": GradientBoostingRegressor(random_state=42),
    "RF (Default)": RandomForestRegressor(random_state=42),
    "LGBM (Default)": lgb.LGBMRegressor(random_state=42, verbosity=-1)
}

baseline_cc50 = []
for name, model in standard_models.items():
    model.fit(X_train_cc, y_train_cc)
    p_tr= model.predict(X_train_cc)
    p_te= model.predict(X_test_cc)
    baseline_cc50.append({
        "Model": name,
        "Train RMSE": np.sqrt(mean_squared_error(y_train_cc, p_tr)),
        "Test RMSE": np.sqrt(mean_squared_error(y_test_cc, p_te)),
        "Test R2": r2_score(y_test_cc, p_te)
    })
display(pd.DataFrame(baseline_cc50))

            Model  Train RMSE  Test RMSE   Test R2
0   GBR (Default)    0.384005   0.568525  0.452285
1    RF (Default)    0.326969   0.547672  0.491729
2  LGBM (Default)    0.297305   0.569912  0.449610

### Полный цикл регрессии для CC50
Сравним GBR, RF и LGBM, подберем гиперпараметры и проверим влияние фильтрации выбросов на предсказание.

In [ ]:
def run_optuna_cc50(model_class, n_trials=150):
    def objective(trial):
        if model_class == GradientBoostingRegressor:
            params = {
                'n_estimators': trial.suggest_int('n_estimators', 10, 400),
                'learning_rate': trial.suggest_float('learning_rate', 0.005, 0.1, log=True),
                'max_depth': trial.suggest_int('max_depth', 1, 7),
                'subsample': trial.suggest_float('subsample', 0.6, 1.0),
                'random_state': 42
            }
        elif model_class == RandomForestRegressor:
            params = {
                'n_estimators': trial.suggest_int('n_estimators', 10, 400),
                'max_depth': trial.suggest_int('max_depth', 1, 15),
                'max_features': trial.suggest_categorical('max_features', ['sqrt', 'log2', None]),
                'random_state': 42
            }
        else: # LGBM
            params = {
                'n_estimators': trial.suggest_int('n_estimators', 10, 400),
                'learning_rate': trial.suggest_float('learning_rate', 0.005, 0.1, log=True),
                'num_leaves': trial.suggest_int('num_leaves', 2, 60),
                'verbosity': -1,
                'random_state': 42
            }

        model = model_class(**params)

        # Обучаем на тренировочных данных
        model.fit(X_train_cc, y_train_cc)

        # Предсказания для замера качества
        train_p = model.predict(X_train_cc)
        test_p = model.predict(X_test_cc)

        train_rmse = np.sqrt(mean_squared_error(y_train_cc, train_p))
        test_rmse = np.sqrt(mean_squared_error(y_test_cc, test_p))

        # Минимизируем тренировочное RMSE + штраф за разницу с тестом
        # Коэффициент штрафа можно регулировать
        gap = abs(train_rmse - test_rmse)
        penalty_factor = 0.5

        return train_rmse + penalty_factor * gap

    study = optuna.create_study(direction='minimize')
    study.optimize(objective, n_trials=n_trials)
    return study.best_params

print("Tuning GBR for CC50 (Test-benchmarked)... ")
best_gbr_cc = run_optuna_cc50(GradientBoostingRegressor)

print("Tuning RF for CC50 (Test-benchmarked)... ")
best_rf_cc = run_optuna_cc50(RandomForestRegressor)

print("Tuning LGBM for CC50 (Test-benchmarked)... ")
best_lgbm_cc = run_optuna_cc50(lgb.LGBMRegressor)

[I 2026-05-23 08:51:07,275] A new study created in memory with name: no-name-a392240e-9c30-4edc-835a-b06699cef1b5

Tuning GBR for CC50 (Test-benchmarked)...

[I 2026-05-23 08:51:28,088] Trial 0 finished with value: 0.45349779309532334 and parameters: {'n_estimators': 365, 'learning_rate': 0.00500187059345782, 'max_depth': 7, 'subsample': 0.8807209984038791}. Best is trial 0 with value: 0.45349779309532334.
[I 2026-05-23 08:51:37,210] Trial 1 finished with value: 0.4292993555336308 and parameters: {'n_estimators': 206, 'learning_rate': 0.034004558865460686, 'max_depth': 7, 'subsample': 0.69157290973724}. Best is trial 1 with value: 0.4292993555336308.
[I 2026-05-23 08:51:58,445] Trial 2 finished with value: 0.4255735726453129 and parameters: {'n_estimators': 365, 'learning_rate': 0.013722275083231355, 'max_depth': 7, 'subsample': 0.8879610281204171}. Best is trial 2 with value: 0.4255735726453129.
[I 2026-05-23 08:52:14,536] Trial 3 finished with value: 0.4324419295322053 and parameters: {'n_estimators': 297, 'learning_rate': 0.028189134625473178, 'max_depth': 6, 'subsample': 0.9896138874966188}. Best is trial 2 with value: 0.4255735726453129.
[I 2026-05-23 08:52:17,249] Trial 4 finished with value: 0.655541450442602 and parameters: {'n_estimators': 83, 'learning_rate': 0.005556669882075516, 'max_depth': 3, 'subsample': 0.9048273965296906}. Best is trial 2 with value: 0.4255735726453129.
[I 2026-05-23 08:52:23,762] Trial 5 finished with value: 0.4903920899081463 and parameters: {'n_estimators': 226, 'learning_rate': 0.012494747967318979, 'max_depth': 4, 'subsample': 0.7818639379553336}. Best is trial 2 with value: 0.4255735726453129.
[I 2026-05-23 08:52:32,063] Trial 6 finished with value: 0.44121623269512905 and parameters: {'n_estimators': 326, 'learning_rate': 0.0602879257786647, 'max_depth': 4, 'subsample': 0.6118339796551752}. Best is trial 2 with value: 0.4255735726453129.
[I 2026-05-23 08:52:49,954] Trial 7 finished with value: 0.42823312710454675 and parameters: {'n_estimators': 336, 'learning_rate': 0.024992542487023657, 'max_depth': 7, 'subsample': 0.822112089584059}. Best is trial 2 with value: 0.4255735726453129.
[I 2026-05-23 08:52:54,993] Trial 8 finished with value: 0.5415429824401039 and parameters: {'n_estimators': 204, 'learning_rate': 0.010882118718584962, 'max_depth': 3, 'subsample': 0.7561651907021313}. Best is trial 2 with value: 0.4255735726453129.
[I 2026-05-23 08:53:02,368] Trial 9 finished with value: 0.4520623799187438 and parameters: {'n_estimators': 306, 'learning_rate': 0.026819442500139904, 'max_depth': 4, 'subsample': 0.6435944408130208}. Best is trial 2 with value: 0.4255735726453129.
[I 2026-05-23 08:53:02,629] Trial 10 finished with value: 0.7237485777554076 and parameters: {'n_estimators': 24, 'learning_rate': 0.012268990696279392, 'max_depth': 1, 'subsample': 0.9944476456368061}. Best is trial 2 with value: 0.4255735726453129.
[I 2026-05-23 08:53:22,478] Trial 11 finished with value: 0.42682050160324037 and parameters: {'n_estimators': 397, 'learning_rate': 0.056241874985189295, 'max_depth': 6, 'subsample': 0.8628067222752461}. Best is trial 2 with value: 0.4255735726453129.
[I 2026-05-23 08:53:41,903] Trial 12 finished with value: 0.4381226480803113 and parameters: {'n_estimators': 390, 'learning_rate': 0.09560952894148403, 'max_depth': 6, 'subsample': 0.9073122442721834}. Best is trial 2 with value: 0.4255735726453129.
[I 2026-05-23 08:54:01,311] Trial 13 finished with value: 0.42792220492894395 and parameters: {'n_estimators': 395, 'learning_rate': 0.052523453811742664, 'max_depth': 6, 'subsample': 0.8519842367052087}. Best is trial 2 with value: 0.4255735726453129.
[I 2026-05-23 08:54:12,526] Trial 14 finished with value: 0.4507247548833303 and parameters: {'n_estimators': 253, 'learning_rate': 0.01680297029103868, 'max_depth': 5, 'subsample': 0.940271002777179}. Best is trial 2 with value: 0.4255735726453129.
[I 2026-05-23 08:54:17,457] Trial 15 finished with value: 0.4499664780046787 and parameters: {'n_estimators': 147, 'learning_rate': 0.04583358893646682, 'max_depth': 5, 'subsample': 0.7358242324042084}. Best is trial 2 with value: 0.4255735726453129.
[I 2026-05-23 08:54:29,914] Trial 16 finished with value: 0.4581431714786849 and parameters: {'n_estimators': 267, 'learning_rate': 0.007923599339386057, 'max_depth': 6, 'subsample': 0.8212834902393059}. Best is trial 2 with value: 0.4255735726453129.
[I 2026-05-23 08:54:33,166] Trial 17 finished with value: 0.5308703268056465 and parameters: {'n_estimators': 353, 'learning_rate': 0.08304868437476189, 'max_depth': 1, 'subsample': 0.9415936349164891}. Best is trial 2 with value: 0.4255735726453129.
[I 2026-05-23 08:54:39,628] Trial 18 finished with value: 0.46964127633755665 and parameters: {'n_estimators': 147, 'learning_rate': 0.017270895503704073, 'max_depth': 5, 'subsample': 0.8651224315634232}. Best is trial 2 with value: 0.4255735726453129.
[I 2026-05-23 08:55:03,928] Trial 19 finished with value: 0.4267541231066744 and parameters: {'n_estimators': 399, 'learning_rate': 0.0175093698333184, 'max_depth': 7, 'subsample': 0.9454938387582371}. Best is trial 2 with value: 0.4255735726453129.
[I 2026-05-23 08:55:20,405] Trial 20 finished with value: 0.4260849483767155 and parameters: {'n_estimators': 276, 'learning_rate': 0.01922899761655341, 'max_depth': 7, 'subsample': 0.9507251809363415}. Best is trial 2 with value: 0.4255735726453129.
[I 2026-05-23 08:55:37,882] Trial 21 finished with value: 0.42934636382863145 and parameters: {'n_estimators': 288, 'learning_rate': 0.015145675451789454, 'max_depth': 7, 'subsample': 0.9486906581953568}. Best is trial 2 with value: 0.4255735726453129.
[I 2026-05-23 08:55:59,762] Trial 22 finished with value: 0.42803804605245965 and parameters: {'n_estimators': 357, 'learning_rate': 0.01915604201003158, 'max_depth': 7, 'subsample': 0.9593821232736846}. Best is trial 2 with value: 0.4255735726453129.
[I 2026-05-23 08:56:18,976] Trial 23 finished with value: 0.4319246684794217 and parameters: {'n_estimators': 327, 'learning_rate': 0.00905850451647606, 'max_depth': 7, 'subsample': 0.9069223613072419}. Best is trial 2 with value: 0.4255735726453129.
[I 2026-05-23 08:56:38,553] Trial 24 finished with value: 0.4276365260957113 and parameters: {'n_estimators': 368, 'learning_rate': 0.03587182760977658, 'max_depth': 6, 'subsample': 0.9716239211782349}. Best is trial 2 with value: 0.4255735726453129.
[I 2026-05-23 08:56:49,589] Trial 25 finished with value: 0.44415510250582496 and parameters: {'n_estimators': 257, 'learning_rate': 0.020781014388763393, 'max_depth': 5, 'subsample': 0.9093241146860788}. Best is trial 2 with value: 0.4255735726453129.
[I 2026-05-23 08:57:00,026] Trial 26 finished with value: 0.4810887883751248 and parameters: {'n_estimators': 175, 'learning_rate': 0.0074230315787674524, 'max_depth': 7, 'subsample': 0.9277473665558319}. Best is trial 2 with value: 0.4255735726453129.
[I 2026-05-23 08:57:15,695] Trial 27 finished with value: 0.43186893829335216 and parameters: {'n_estimators': 315, 'learning_rate': 0.01415652595505721, 'max_depth': 6, 'subsample': 0.8848691787818787}. Best is trial 2 with value: 0.4255735726453129.
[I 2026-05-23 08:57:31,266] Trial 28 finished with value: 0.42607765769007355 and parameters: {'n_estimators': 286, 'learning_rate': 0.02121118611340594, 'max_depth': 7, 'subsample': 0.8328623381060364}. Best is trial 2 with value: 0.4255735726453129.
[I 2026-05-23 08:57:36,170] Trial 29 finished with value: 0.5781914125209986 and parameters: {'n_estimators': 276, 'learning_rate': 0.009604376306743042, 'max_depth': 2, 'subsample': 0.8361255554142278}. Best is trial 2 with value: 0.4255735726453129.
[I 2026-05-23 08:57:43,976] Trial 30 finished with value: 0.44888806560546624 and parameters: {'n_estimators': 219, 'learning_rate': 0.023100487088559735, 'max_depth': 5, 'subsample': 0.7802328980509274}. Best is trial 2 with value: 0.4255735726453129.
[I 2026-05-23 08:58:05,286] Trial 31 finished with value: 0.4250105482928708 and parameters: {'n_estimators': 369, 'learning_rate': 0.019841143323688738, 'max_depth': 7, 'subsample': 0.8906044235446077}. Best is trial 31 with value: 0.4250105482928708.
[I 2026-05-23 08:58:26,369] Trial 32 finished with value: 0.42062681286914694 and parameters: {'n_estimators': 359, 'learning_rate': 0.03450845425777368, 'max_depth': 7, 'subsample': 0.8890550774504705}. Best is trial 32 with value: 0.42062681286914694.
[I 2026-05-23 08:58:47,006] Trial 33 finished with value: 0.4194746880859759 and parameters: {'n_estimators': 367, 'learning_rate': 0.03695239002700137, 'max_depth': 7, 'subsample': 0.8817261889137016}. Best is trial 33 with value: 0.4194746880859759.
[I 2026-05-23 08:59:05,353] Trial 34 finished with value: 0.43037816285490393 and parameters: {'n_estimators': 367, 'learning_rate': 0.03345849581411418, 'max_depth': 6, 'subsample': 0.8810713969370693}. Best is trial 33 with value: 0.4194746880859759.
[I 2026-05-23 08:59:24,945] Trial 35 finished with value: 0.42192713855742386 and parameters: {'n_estimators': 345, 'learning_rate': 0.03899773391296397, 'max_depth': 7, 'subsample': 0.8855166113762117}. Best is trial 33 with value: 0.4194746880859759.
[I 2026-05-23 08:59:41,011] Trial 36 finished with value: 0.43252941819407087 and parameters: {'n_estimators': 342, 'learning_rate': 0.03985861316769924, 'max_depth': 6, 'subsample': 0.806160376609524}. Best is trial 33 with value: 0.4194746880859759.
[I 2026-05-23 09:00:01,230] Trial 37 finished with value: 0.42806545867483353 and parameters: {'n_estimators': 370, 'learning_rate': 0.0708628155227545, 'max_depth': 7, 'subsample': 0.858017578235676}. Best is trial 33 with value: 0.4194746880859759.
[I 2026-05-23 09:00:20,498] Trial 38 finished with value: 0.4260204427125048 and parameters: {'n_estimators': 314, 'learning_rate': 0.029798515881776354, 'max_depth': 7, 'subsample': 0.9249232532982647}. Best is trial 33 with value: 0.4194746880859759.
[I 2026-05-23 09:00:29,195] Trial 39 finished with value: 0.45887654957517443 and parameters: {'n_estimators': 342, 'learning_rate': 0.04340525793802924, 'max_depth': 3, 'subsample': 0.8891898078560139}. Best is trial 33 with value: 0.4194746880859759.
[I 2026-05-23 09:00:49,691] Trial 40 finished with value: 0.4249526087341843 and parameters: {'n_estimators': 375, 'learning_rate': 0.029217934498050036, 'max_depth': 7, 'subsample': 0.8455860501316322}. Best is trial 33 with value: 0.4194746880859759.
[I 2026-05-23 09:01:10,869] Trial 41 finished with value: 0.42779783534331084 and parameters: {'n_estimators': 377, 'learning_rate': 0.03315783469167076, 'max_depth': 7, 'subsample': 0.8518499678009905}. Best is trial 33 with value: 0.4194746880859759.
[I 2026-05-23 09:01:28,655] Trial 42 finished with value: 0.4277600676882475 and parameters: {'n_estimators': 345, 'learning_rate': 0.0278717913700328, 'max_depth': 7, 'subsample': 0.7988711952093391}. Best is trial 33 with value: 0.4194746880859759.
[I 2026-05-23 09:01:47,813] Trial 43 finished with value: 0.42845353155924654 and parameters: {'n_estimators': 382, 'learning_rate': 0.047960880558607644, 'max_depth': 6, 'subsample': 0.8861636271214904}. Best is trial 33 with value: 0.4194746880859759.
[I 2026-05-23 09:02:05,137] Trial 44 finished with value: 0.4219083988579416 and parameters: {'n_estimators': 326, 'learning_rate': 0.03764100418277194, 'max_depth': 7, 'subsample': 0.836585528500108}. Best is trial 33 with value: 0.4194746880859759.
[I 2026-05-23 09:02:21,273] Trial 45 finished with value: 0.42762283155273684 and parameters: {'n_estimators': 327, 'learning_rate': 0.03911592293663764, 'max_depth': 7, 'subsample': 0.760633216829982}. Best is trial 33 with value: 0.4194746880859759.
[I 2026-05-23 09:02:35,958] Trial 46 finished with value: 0.42349364827224384 and parameters: {'n_estimators': 301, 'learning_rate': 0.06628621810324938, 'max_depth': 6, 'subsample': 0.8407882456376627}. Best is trial 33 with value: 0.4194746880859759.
[I 2026-05-23 09:02:50,307] Trial 47 finished with value: 0.43228805353033795 and parameters: {'n_estimators': 303, 'learning_rate': 0.06287557240446667, 'max_depth': 6, 'subsample': 0.8175070013751019}. Best is trial 33 with value: 0.4194746880859759.
[I 2026-05-23 09:02:50,749] Trial 48 finished with value: 0.5956084907292316 and parameters: {'n_estimators': 10, 'learning_rate': 0.05252186915956297, 'max_depth': 6, 'subsample': 0.7859086140619163}. Best is trial 33 with value: 0.4194746880859759.
[I 2026-05-23 09:02:58,545] Trial 49 finished with value: 0.43749112930221745 and parameters: {'n_estimators': 236, 'learning_rate': 0.06913735249806519, 'max_depth': 4, 'subsample': 0.9201804183188607}. Best is trial 33 with value: 0.4194746880859759.
[I 2026-05-23 09:03:11,973] Trial 50 finished with value: 0.4357190866481911 and parameters: {'n_estimators': 318, 'learning_rate': 0.02477381046206279, 'max_depth': 6, 'subsample': 0.719784453120645}. Best is trial 33 with value: 0.4194746880859759.
[I 2026-05-23 09:03:31,731] Trial 51 finished with value: 0.4261503895502927 and parameters: {'n_estimators': 356, 'learning_rate': 0.03098610659326621, 'max_depth': 7, 'subsample': 0.8382505141330849}. Best is trial 33 with value: 0.4194746880859759.
[I 2026-05-23 09:03:50,057] Trial 52 finished with value: 0.4240987869234353 and parameters: {'n_estimators': 333, 'learning_rate': 0.03710329999422004, 'max_depth': 7, 'subsample': 0.8628122745002998}. Best is trial 33 with value: 0.4194746880859759.
[I 2026-05-23 09:04:07,454] Trial 53 finished with value: 0.4257754644512851 and parameters: {'n_estimators': 301, 'learning_rate': 0.03850902647184296, 'max_depth': 7, 'subsample': 0.8696689399402363}. Best is trial 33 with value: 0.4194746880859759.
[I 2026-05-23 09:04:25,950] Trial 54 finished with value: 0.42251386136799274 and parameters: {'n_estimators': 335, 'learning_rate': 0.04356677188193726, 'max_depth': 7, 'subsample': 0.8695649464650316}. Best is trial 33 with value: 0.4194746880859759.
[I 2026-05-23 09:04:43,557] Trial 55 finished with value: 0.42656045907749246 and parameters: {'n_estimators': 351, 'learning_rate': 0.044181920450294454, 'max_depth': 6, 'subsample': 0.8705115870059648}. Best is trial 33 with value: 0.4194746880859759.
[I 2026-05-23 09:04:54,626] Trial 56 finished with value: 0.43415298922374534 and parameters: {'n_estimators': 293, 'learning_rate': 0.05386730184250015, 'max_depth': 5, 'subsample': 0.8198557818452992}. Best is trial 33 with value: 0.4194746880859759.
[I 2026-05-23 09:05:17,272] Trial 57 finished with value: 0.427668613687872 and parameters: {'n_estimators': 385, 'learning_rate': 0.08979283694029042, 'max_depth': 7, 'subsample': 0.8996910030222685}. Best is trial 33 with value: 0.4194746880859759.
[I 2026-05-23 09:05:31,418] Trial 58 finished with value: 0.4244243044694397 and parameters: {'n_estimators': 315, 'learning_rate': 0.07767315495444937, 'max_depth': 6, 'subsample': 0.8031793561266789}. Best is trial 33 with value: 0.4194746880859759.
[I 2026-05-23 09:05:35,722] Trial 59 finished with value: 0.4345085172207229 and parameters: {'n_estimators': 87, 'learning_rate': 0.0621785711930822, 'max_depth': 7, 'subsample': 0.6549893309971564}. Best is trial 33 with value: 0.4194746880859759.
[I 2026-05-23 09:05:54,487] Trial 60 finished with value: 0.4252099574767383 and parameters: {'n_estimators': 337, 'learning_rate': 0.04794416162452694, 'max_depth': 7, 'subsample': 0.871566679594971}. Best is trial 33 with value: 0.4194746880859759.
[I 2026-05-23 09:06:13,284] Trial 61 finished with value: 0.4255833754526248 and parameters: {'n_estimators': 326, 'learning_rate': 0.041896397829750354, 'max_depth': 7, 'subsample': 0.8595745681825135}. Best is trial 33 with value: 0.4194746880859759.
[I 2026-05-23 09:06:31,228] Trial 62 finished with value: 0.42792598964401785 and parameters: {'n_estimators': 331, 'learning_rate': 0.03796882805166025, 'max_depth': 7, 'subsample': 0.8429006772893507}. Best is trial 33 with value: 0.4194746880859759.
[I 2026-05-23 09:06:54,742] Trial 63 finished with value: 0.4249259892315932 and parameters: {'n_estimators': 397, 'learning_rate': 0.034838336840073945, 'max_depth': 7, 'subsample': 0.90997335519988}. Best is trial 33 with value: 0.4194746880859759.
[I 2026-05-23 09:07:15,836] Trial 64 finished with value: 0.4256050289621471 and parameters: {'n_estimators': 357, 'learning_rate': 0.02540122545160786, 'max_depth': 7, 'subsample': 0.8993916701943524}. Best is trial 33 with value: 0.4194746880859759.
[I 2026-05-23 09:07:33,118] Trial 65 finished with value: 0.4260125365910986 and parameters: {'n_estimators': 356, 'learning_rate': 0.031586249883806906, 'max_depth': 6, 'subsample': 0.8790102043419739}. Best is trial 33 with value: 0.4194746880859759.
[I 2026-05-23 09:07:48,258] Trial 66 finished with value: 0.4246086064589266 and parameters: {'n_estimators': 279, 'learning_rate': 0.050367263522978725, 'max_depth': 7, 'subsample': 0.8327870686114351}. Best is trial 33 with value: 0.4194746880859759.
[I 2026-05-23 09:08:00,676] Trial 67 finished with value: 0.4247414154699276 and parameters: {'n_estimators': 254, 'learning_rate': 0.05888556787705961, 'max_depth': 6, 'subsample': 0.8516486707502042}. Best is trial 33 with value: 0.4194746880859759.
[I 2026-05-23 09:08:19,253] Trial 68 finished with value: 0.42872046407027653 and parameters: {'n_estimators': 337, 'learning_rate': 0.034957104781723626, 'max_depth': 7, 'subsample': 0.8231114530188259}. Best is trial 33 with value: 0.4194746880859759.
[I 2026-05-23 09:08:35,304] Trial 69 finished with value: 0.48260400932692377 and parameters: {'n_estimators': 306, 'learning_rate': 0.005091607259415208, 'max_depth': 6, 'subsample': 0.975806320310977}. Best is trial 33 with value: 0.4194746880859759.
[I 2026-05-23 09:08:40,847] Trial 70 finished with value: 0.4949969004435776 and parameters: {'n_estimators': 320, 'learning_rate': 0.04545535572874619, 'max_depth': 2, 'subsample': 0.9177913497653973}. Best is trial 33 with value: 0.4194746880859759.
[I 2026-05-23 09:08:52,783] Trial 71 finished with value: 0.4314916566544087 and parameters: {'n_estimators': 312, 'learning_rate': 0.08554787268000358, 'max_depth': 5, 'subsample': 0.7966239662440597}. Best is trial 33 with value: 0.4194746880859759.
[I 2026-05-23 09:09:08,686] Trial 72 finished with value: 0.43022759444597375 and parameters: {'n_estimators': 293, 'learning_rate': 0.07753590177543424, 'max_depth': 7, 'subsample': 0.8108604843189661}. Best is trial 33 with value: 0.4194746880859759.
[I 2026-05-23 09:09:23,717] Trial 73 finished with value: 0.42849608143444 and parameters: {'n_estimators': 343, 'learning_rate': 0.07664234188388279, 'max_depth': 6, 'subsample': 0.7697724692755297}. Best is trial 33 with value: 0.4194746880859759.
[I 2026-05-23 09:09:43,696] Trial 74 finished with value: 0.4244214263786676 and parameters: {'n_estimators': 365, 'learning_rate': 0.0672826244953642, 'max_depth': 7, 'subsample': 0.8606992432635762}. Best is trial 33 with value: 0.4194746880859759.
[I 2026-05-23 09:10:04,967] Trial 75 finished with value: 0.42170507219371706 and parameters: {'n_estimators': 362, 'learning_rate': 0.06690498127518017, 'max_depth': 7, 'subsample': 0.8939924292696713}. Best is trial 33 with value: 0.4194746880859759.
[I 2026-05-23 09:10:28,365] Trial 76 finished with value: 0.4327904803732039 and parameters: {'n_estimators': 388, 'learning_rate': 0.057523420974977334, 'max_depth': 7, 'subsample': 0.9302613413836706}. Best is trial 33 with value: 0.4194746880859759.
[I 2026-05-23 09:10:48,409] Trial 77 finished with value: 0.4251529470984057 and parameters: {'n_estimators': 349, 'learning_rate': 0.041687725215010143, 'max_depth': 7, 'subsample': 0.8953358604077318}. Best is trial 33 with value: 0.4194746880859759.
[I 2026-05-23 09:11:10,112] Trial 78 finished with value: 0.4235424677696843 and parameters: {'n_estimators': 378, 'learning_rate': 0.09884096579651633, 'max_depth': 7, 'subsample': 0.8764322089289228}. Best is trial 33 with value: 0.4194746880859759.

Tuning RF for CC50 (Test-benchmarked)...

[I 2026-05-23 09:30:17,982] Trial 0 finished with value: 0.6246211254104586 and parameters: {'n_estimators': 396, 'max_depth': 2, 'max_features': None}. Best is trial 0 with value: 0.6246211254104586.
[I 2026-05-23 09:30:18,828] Trial 1 finished with value: 0.6133210942057192 and parameters: {'n_estimators': 303, 'max_depth': 3, 'max_features': 'sqrt'}. Best is trial 1 with value: 0.6133210942057192.
[I 2026-05-23 09:30:20,106] Trial 2 finished with value: 0.686602557762939 and parameters: {'n_estimators': 176, 'max_depth': 1, 'max_features': None}. Best is trial 1 with value: 0.6133210942057192.
[I 2026-05-23 09:30:20,436] Trial 3 finished with value: 0.43930141157937175 and parameters: {'n_estimators': 49, 'max_depth': 14, 'max_features': 'sqrt'}. Best is trial 3 with value: 0.43930141157937175.
[I 2026-05-23 09:30:32,563] Trial 4 finished with value: 0.440166872356096 and parameters: {'n_estimators': 174, 'max_depth': 15, 'max_features': None}. Best is trial 3 with value: 0.43930141157937175.
[I 2026-05-23 09:30:33,124] Trial 5 finished with value: 0.45296098586733446 and parameters: {'n_estimators': 92, 'max_depth': 11, 'max_features': 'sqrt'}. Best is trial 3 with value: 0.43930141157937175.
[I 2026-05-23 09:30:33,695] Trial 6 finished with value: 0.6560313297249059 and parameters: {'n_estimators': 251, 'max_depth': 2, 'max_features': 'sqrt'}. Best is trial 3 with value: 0.43930141157937175.
[I 2026-05-23 09:30:35,331] Trial 7 finished with value: 0.4447186429583053 and parameters: {'n_estimators': 249, 'max_depth': 13, 'max_features': 'sqrt'}. Best is trial 3 with value: 0.43930141157937175.
[I 2026-05-23 09:30:36,422] Trial 8 finished with value: 0.44041708839135396 and parameters: {'n_estimators': 163, 'max_depth': 14, 'max_features': 'sqrt'}. Best is trial 3 with value: 0.43930141157937175.
[I 2026-05-23 09:30:38,916] Trial 9 finished with value: 0.4496680536979653 and parameters: {'n_estimators': 292, 'max_depth': 11, 'max_features': 'sqrt'}. Best is trial 3 with value: 0.43930141157937175.
[I 2026-05-23 09:30:39,005] Trial 10 finished with value: 0.5268059540477483 and parameters: {'n_estimators': 12, 'max_depth': 7, 'max_features': 'log2'}. Best is trial 3 with value: 0.43930141157937175.
[I 2026-05-23 09:30:44,578] Trial 11 finished with value: 0.43839008155144366 and parameters: {'n_estimators': 85, 'max_depth': 15, 'max_features': None}. Best is trial 11 with value: 0.43839008155144366.
[I 2026-05-23 09:30:44,652] Trial 12 finished with value: 0.49821410638274033 and parameters: {'n_estimators': 16, 'max_depth': 8, 'max_features': 'log2'}. Best is trial 11 with value: 0.43839008155144366.
[I 2026-05-23 09:30:49,545] Trial 13 finished with value: 0.44202985235852543 and parameters: {'n_estimators': 80, 'max_depth': 12, 'max_features': None}. Best is trial 11 with value: 0.43839008155144366.
[I 2026-05-23 09:30:55,941] Trial 14 finished with value: 0.4384888152943727 and parameters: {'n_estimators': 88, 'max_depth': 15, 'max_features': None}. Best is trial 11 with value: 0.43839008155144366.
[I 2026-05-23 09:30:59,490] Trial 15 finished with value: 0.5141801358926859 and parameters: {'n_estimators': 120, 'max_depth': 5, 'max_features': None}. Best is trial 11 with value: 0.43839008155144366.
[I 2026-05-23 09:31:06,949] Trial 16 finished with value: 0.44913591908796247 and parameters: {'n_estimators': 126, 'max_depth': 10, 'max_features': None}. Best is trial 11 with value: 0.43839008155144366.
[I 2026-05-23 09:31:11,377] Trial 17 finished with value: 0.43927310442101 and parameters: {'n_estimators': 67, 'max_depth': 15, 'max_features': None}. Best is trial 11 with value: 0.43839008155144366.
[I 2026-05-23 09:31:18,482] Trial 18 finished with value: 0.45461151030336844 and parameters: {'n_estimators': 128, 'max_depth': 9, 'max_features': None}. Best is trial 11 with value: 0.43839008155144366.
[I 2026-05-23 09:31:19,377] Trial 19 finished with value: 0.44320548696569906 and parameters: {'n_estimators': 203, 'max_depth': 13, 'max_features': 'log2'}. Best is trial 11 with value: 0.43839008155144366.
[I 2026-05-23 09:31:31,706] Trial 20 finished with value: 0.5145923306369109 and parameters: {'n_estimators': 396, 'max_depth': 5, 'max_features': None}. Best is trial 11 with value: 0.43839008155144366.
[I 2026-05-23 09:31:35,670] Trial 21 finished with value: 0.4387920693545439 and parameters: {'n_estimators': 60, 'max_depth': 15, 'max_features': None}. Best is trial 11 with value: 0.43839008155144366.
[I 2026-05-23 09:31:38,038] Trial 22 finished with value: 0.4396039629612823 and parameters: {'n_estimators': 36, 'max_depth': 15, 'max_features': None}. Best is trial 11 with value: 0.43839008155144366.
[I 2026-05-23 09:31:44,827] Trial 23 finished with value: 0.44050760451656745 and parameters: {'n_estimators': 98, 'max_depth': 13, 'max_features': None}. Best is trial 11 with value: 0.43839008155144366.
[I 2026-05-23 09:31:47,880] Trial 24 finished with value: 0.4427322337417947 and parameters: {'n_estimators': 51, 'max_depth': 12, 'max_features': None}. Best is trial 11 with value: 0.43839008155144366.
[I 2026-05-23 09:31:57,818] Trial 25 finished with value: 0.44116203119173525 and parameters: {'n_estimators': 143, 'max_depth': 14, 'max_features': None}. Best is trial 11 with value: 0.43839008155144366.
[I 2026-05-23 09:31:58,253] Trial 26 finished with value: 0.4362301603830767 and parameters: {'n_estimators': 88, 'max_depth': 15, 'max_features': 'log2'}. Best is trial 26 with value: 0.4362301603830767.
[I 2026-05-23 09:31:59,256] Trial 27 finished with value: 0.44644392674568867 and parameters: {'n_estimators': 104, 'max_depth': 12, 'max_features': 'log2'}. Best is trial 26 with value: 0.4362301603830767.
[I 2026-05-23 09:31:59,859] Trial 28 finished with value: 0.459958266609104 and parameters: {'n_estimators': 149, 'max_depth': 10, 'max_features': 'log2'}. Best is trial 26 with value: 0.4362301603830767.
[I 2026-05-23 09:32:00,808] Trial 29 finished with value: 0.44197607113849374 and parameters: {'n_estimators': 207, 'max_depth': 14, 'max_features': 'log2'}. Best is trial 26 with value: 0.4362301603830767.
[I 2026-05-23 09:32:01,699] Trial 30 finished with value: 0.4429507414537479 and parameters: {'n_estimators': 198, 'max_depth': 13, 'max_features': 'log2'}. Best is trial 26 with value: 0.4362301603830767.
[I 2026-05-23 09:32:06,875] Trial 31 finished with value: 0.438382767665475 and parameters: {'n_estimators': 71, 'max_depth': 15, 'max_features': None}. Best is trial 26 with value: 0.4362301603830767.
[I 2026-05-23 09:32:31,445] Trial 32 finished with value: 0.4396209657864356 and parameters: {'n_estimators': 354, 'max_depth': 15, 'max_features': None}. Best is trial 26 with value: 0.4362301603830767.
[I 2026-05-23 09:32:37,174] Trial 33 finished with value: 0.4385741309323001 and parameters: {'n_estimators': 81, 'max_depth': 14, 'max_features': None}. Best is trial 26 with value: 0.4362301603830767.
[I 2026-05-23 09:32:37,350] Trial 34 finished with value: 0.43939130470765675 and parameters: {'n_estimators': 30, 'max_depth': 15, 'max_features': 'log2'}. Best is trial 26 with value: 0.4362301603830767.
[I 2026-05-23 09:32:45,019] Trial 35 finished with value: 0.44115661770235903 and parameters: {'n_estimators': 108, 'max_depth': 14, 'max_features': None}. Best is trial 26 with value: 0.4362301603830767.
[I 2026-05-23 09:32:49,615] Trial 36 finished with value: 0.4407381275998704 and parameters: {'n_estimators': 74, 'max_depth': 12, 'max_features': None}. Best is trial 26 with value: 0.4362301603830767.
[I 2026-05-23 09:32:49,823] Trial 37 finished with value: 0.449279101106387 and parameters: {'n_estimators': 40, 'max_depth': 13, 'max_features': 'log2'}. Best is trial 26 with value: 0.4362301603830767.
[I 2026-05-23 09:32:58,988] Trial 38 finished with value: 0.44637389941928407 and parameters: {'n_estimators': 147, 'max_depth': 11, 'max_features': None}. Best is trial 26 with value: 0.4362301603830767.
[I 2026-05-23 09:33:11,821] Trial 39 finished with value: 0.4399578513397204 and parameters: {'n_estimators': 181, 'max_depth': 15, 'max_features': None}. Best is trial 26 with value: 0.4362301603830767.
[I 2026-05-23 09:33:12,466] Trial 40 finished with value: 0.44030672431570983 and parameters: {'n_estimators': 91, 'max_depth': 14, 'max_features': 'sqrt'}. Best is trial 26 with value: 0.4362301603830767.
[I 2026-05-23 09:33:17,597] Trial 41 finished with value: 0.4389563097241022 and parameters: {'n_estimators': 80, 'max_depth': 14, 'max_features': None}. Best is trial 26 with value: 0.4362301603830767.
[I 2026-05-23 09:33:22,282] Trial 42 finished with value: 0.43956145272378 and parameters: {'n_estimators': 64, 'max_depth': 15, 'max_features': None}. Best is trial 26 with value: 0.4362301603830767.
[I 2026-05-23 09:33:29,748] Trial 43 finished with value: 0.4410379410465678 and parameters: {'n_estimators': 115, 'max_depth': 13, 'max_features': None}. Best is trial 26 with value: 0.4362301603830767.
[I 2026-05-23 09:33:36,497] Trial 44 finished with value: 0.4393148455939972 and parameters: {'n_estimators': 94, 'max_depth': 14, 'max_features': None}. Best is trial 26 with value: 0.4362301603830767.
[I 2026-05-23 09:33:36,850] Trial 45 finished with value: 0.4395661630264397 and parameters: {'n_estimators': 48, 'max_depth': 14, 'max_features': 'sqrt'}. Best is trial 26 with value: 0.4362301603830767.
[I 2026-05-23 09:33:37,877] Trial 46 finished with value: 0.49373564318925006 and parameters: {'n_estimators': 29, 'max_depth': 6, 'max_features': None}. Best is trial 26 with value: 0.4362301603830767.
[I 2026-05-23 09:33:38,521] Trial 47 finished with value: 0.43690153523761815 and parameters: {'n_estimators': 135, 'max_depth': 15, 'max_features': 'log2'}. Best is trial 26 with value: 0.4362301603830767.
[I 2026-05-23 09:33:38,766] Trial 48 finished with value: 0.7063473857047617 and parameters: {'n_estimators': 130, 'max_depth': 1, 'max_features': 'log2'}. Best is trial 26 with value: 0.4362301603830767.
[I 2026-05-23 09:33:39,117] Trial 49 finished with value: 0.6274665382780222 and parameters: {'n_estimators': 161, 'max_depth': 3, 'max_features': 'log2'}. Best is trial 26 with value: 0.4362301603830767.
[I 2026-05-23 09:33:40,097] Trial 50 finished with value: 0.45236100341114416 and parameters: {'n_estimators': 241, 'max_depth': 11, 'max_features': 'log2'}. Best is trial 26 with value: 0.4362301603830767.
[I 2026-05-23 09:33:40,486] Trial 51 finished with value: 0.4367149357301628 and parameters: {'n_estimators': 81, 'max_depth': 15, 'max_features': 'log2'}. Best is trial 26 with value: 0.4362301603830767.
[I 2026-05-23 09:33:40,786] Trial 52 finished with value: 0.43933001751762685 and parameters: {'n_estimators': 57, 'max_depth': 15, 'max_features': 'log2'}. Best is trial 26 with value: 0.4362301603830767.
[I 2026-05-23 09:33:41,333] Trial 53 finished with value: 0.4367888124335393 and parameters: {'n_estimators': 114, 'max_depth': 15, 'max_features': 'log2'}. Best is trial 26 with value: 0.4362301603830767.
[I 2026-05-23 09:33:41,880] Trial 54 finished with value: 0.4367888124335393 and parameters: {'n_estimators': 114, 'max_depth': 15, 'max_features': 'log2'}. Best is trial 26 with value: 0.4362301603830767.
[I 2026-05-23 09:33:42,406] Trial 55 finished with value: 0.44525375472325535 and parameters: {'n_estimators': 116, 'max_depth': 13, 'max_features': 'log2'}. Best is trial 26 with value: 0.4362301603830767.
[I 2026-05-23 09:33:43,052] Trial 56 finished with value: 0.43712035924639636 and parameters: {'n_estimators': 136, 'max_depth': 15, 'max_features': 'log2'}. Best is trial 26 with value: 0.4362301603830767.
[I 2026-05-23 09:33:43,827] Trial 57 finished with value: 0.44344420274347507 and parameters: {'n_estimators': 171, 'max_depth': 13, 'max_features': 'log2'}. Best is trial 26 with value: 0.4362301603830767.
[I 2026-05-23 09:33:44,472] Trial 58 finished with value: 0.43712035924639636 and parameters: {'n_estimators': 136, 'max_depth': 15, 'max_features': 'log2'}. Best is trial 26 with value: 0.4362301603830767.
[I 2026-05-23 09:33:45,164] Trial 59 finished with value: 0.4460785690801331 and parameters: {'n_estimators': 160, 'max_depth': 12, 'max_features': 'log2'}. Best is trial 26 with value: 0.4362301603830767.
[I 2026-05-23 09:33:46,027] Trial 60 finished with value: 0.4428573888933427 and parameters: {'n_estimators': 184, 'max_depth': 14, 'max_features': 'log2'}. Best is trial 26 with value: 0.4362301603830767.
[I 2026-05-23 09:33:46,906] Trial 61 finished with value: 0.43712035924639636 and parameters: {'n_estimators': 136, 'max_depth': 15, 'max_features': 'log2'}. Best is trial 26 with value: 0.4362301603830767.
[I 2026-05-23 09:33:47,694] Trial 62 finished with value: 0.4368026053955973 and parameters: {'n_estimators': 109, 'max_depth': 15, 'max_features': 'log2'}. Best is trial 26 with value: 0.4362301603830767.
[I 2026-05-23 09:33:48,438] Trial 63 finished with value: 0.44449438305457234 and parameters: {'n_estimators': 105, 'max_depth': 14, 'max_features': 'log2'}. Best is trial 26 with value: 0.4362301603830767.
[I 2026-05-23 09:33:49,167] Trial 64 finished with value: 0.4361333415660916 and parameters: {'n_estimators': 119, 'max_depth': 15, 'max_features': 'log2'}. Best is trial 64 with value: 0.4361333415660916.
[I 2026-05-23 09:33:49,732] Trial 65 finished with value: 0.4450297210648946 and parameters: {'n_estimators': 123, 'max_depth': 13, 'max_features': 'log2'}. Best is trial 64 with value: 0.4361333415660916.
[I 2026-05-23 09:33:50,205] Trial 66 finished with value: 0.44408666655934015 and parameters: {'n_estimators': 98, 'max_depth': 14, 'max_features': 'log2'}. Best is trial 64 with value: 0.4361333415660916.
[I 2026-05-23 09:33:50,595] Trial 67 finished with value: 0.48720813127974616 and parameters: {'n_estimators': 113, 'max_depth': 8, 'max_features': 'log2'}. Best is trial 64 with value: 0.4361333415660916.
[I 2026-05-23 09:33:51,639] Trial 68 finished with value: 0.43586015213379115 and parameters: {'n_estimators': 224, 'max_depth': 15, 'max_features': 'log2'}. Best is trial 68 with value: 0.43586015213379115.
[I 2026-05-23 09:33:52,470] Trial 69 finished with value: 0.47223163585645833 and parameters: {'n_estimators': 231, 'max_depth': 9, 'max_features': 'log2'}. Best is trial 68 with value: 0.43586015213379115.
[I 2026-05-23 09:33:53,470] Trial 70 finished with value: 0.44174386924936204 and parameters: {'n_estimators': 219, 'max_depth': 14, 'max_features': 'log2'}. Best is trial 68 with value: 0.43586015213379115.
[I 2026-05-23 09:33:54,715] Trial 71 finished with value: 0.4366521901855186 and parameters: {'n_estimators': 268, 'max_depth': 15, 'max_features': 'log2'}. Best is trial 68 with value: 0.43586015213379115.
[I 2026-05-23 09:33:55,618] Trial 72 finished with value: 0.4360049159063456 and parameters: {'n_estimators': 193, 'max_depth': 15, 'max_features': 'log2'}. Best is trial 68 with value: 0.43586015213379115.
[I 2026-05-23 09:33:56,885] Trial 73 finished with value: 0.4367124662538113 and parameters: {'n_estimators': 270, 'max_depth': 15, 'max_features': 'log2'}. Best is trial 68 with value: 0.43586015213379115.
[I 2026-05-23 09:33:58,155] Trial 74 finished with value: 0.441687844969045 and parameters: {'n_estimators': 273, 'max_depth': 14, 'max_features': 'log2'}. Best is trial 68 with value: 0.43586015213379115.
[I 2026-05-23 09:34:00,015] Trial 75 finished with value: 0.4370720110967584 and parameters: {'n_estimators': 319, 'max_depth': 15, 'max_features': 'log2'}. Best is trial 68 with value: 0.43586015213379115.
[I 2026-05-23 09:34:02,449] Trial 76 finished with value: 0.4403012458679634 and parameters: {'n_estimators': 286, 'max_depth': 14, 'max_features': 'sqrt'}. Best is trial 68 with value: 0.43586015213379115.
[I 2026-05-23 09:34:03,745] Trial 77 finished with value: 0.4431057426933084 and parameters: {'n_estimators': 270, 'max_depth': 13, 'max_features': 'log2'}. Best is trial 68 with value: 0.43586015213379115.
[I 2026-05-23 09:34:05,131] Trial 78 finished with value: 0.43716372670592907 and parameters: {'n_estimators': 294, 'max_depth': 15, 'max_features': 'log2'}. Best is trial 68 with value: 0.43586015213379115.
[I 2026-05-23 09:34:06,576] Trial 79 finished with value: 0.44180786621025403 and parameters: {'n_estimators': 317, 'max_depth': 14, 'max_features': 'log2'}. Best is trial 68 with value: 0.43586015213379115.
[I 2026-05-23 09:34:07,800] Trial 80 finished with value: 0.43659112016596346 and parameters: {'n_estimators': 259, 'max_depth': 15, 'max_features': 'log2'}. Best is trial 68 with value: 0.43586015213379115.
[I 2026-05-23 09:34:09,050] Trial 81 finished with value: 0.43642908002185987 and parameters: {'n_estimators': 264, 'max_depth': 15, 'max_features': 'log2'}. Best is trial 68 with value: 0.43586015213379115.
[I 2026-05-23 09:34:10,244] Trial 82 finished with value: 0.4365870573779836 and parameters: {'n_estimators': 255, 'max_depth': 15, 'max_features': 'log2'}. Best is trial 68 with value: 0.43586015213379115.
[I 2026-05-23 09:34:11,468] Trial 83 finished with value: 0.44139410098777665 and parameters: {'n_estimators': 260, 'max_depth': 14, 'max_features': 'log2'}. Best is trial 68 with value: 0.43586015213379115.
[I 2026-05-23 09:34:13,164] Trial 84 finished with value: 0.4358038399164713 and parameters: {'n_estimators': 248, 'max_depth': 15, 'max_features': 'log2'}. Best is trial 84 with value: 0.4358038399164713.
[I 2026-05-23 09:34:14,238] Trial 85 finished with value: 0.5078935729336613 and parameters: {'n_estimators': 245, 'max_depth': 7, 'max_features': 'log2'}. Best is trial 84 with value: 0.4358038399164713.
[I 2026-05-23 09:34:15,988] Trial 86 finished with value: 0.44052588602789866 and parameters: {'n_estimators': 257, 'max_depth': 15, 'max_features': 'sqrt'}. Best is trial 84 with value: 0.4358038399164713.
[I 2026-05-23 09:34:17,030] Trial 87 finished with value: 0.4416072716173597 and parameters: {'n_estimators': 224, 'max_depth': 14, 'max_features': 'log2'}. Best is trial 84 with value: 0.4358038399164713.
[I 2026-05-23 09:34:18,022] Trial 88 finished with value: 0.4361622136489576 and parameters: {'n_estimators': 211, 'max_depth': 15, 'max_features': 'log2'}. Best is trial 84 with value: 0.4358038399164713.
[I 2026-05-23 09:34:18,933] Trial 89 finished with value: 0.4422925264728635 and parameters: {'n_estimators': 195, 'max_depth': 14, 'max_features': 'log2'}. Best is trial 84 with value: 0.4358038399164713.
[I 2026-05-23 09:34:19,972] Trial 90 finished with value: 0.4436052157858016 and parameters: {'n_estimators': 235, 'max_depth': 13, 'max_features': 'log2'}. Best is trial 84 with value: 0.4358038399164713.
[I 2026-05-23 09:34:20,967] Trial 91 finished with value: 0.43603065638967486 and parameters: {'n_estimators': 209, 'max_depth': 15, 'max_features': 'log2'}. Best is trial 84 with value: 0.4358038399164713.
[I 2026-05-23 09:34:21,956] Trial 92 finished with value: 0.43612760623001473 and parameters: {'n_estimators': 210, 'max_depth': 15, 'max_features': 'log2'}. Best is trial 84 with value: 0.4358038399164713.
[I 2026-05-23 09:34:22,933] Trial 93 finished with value: 0.435940159501783 and parameters: {'n_estimators': 208, 'max_depth': 15, 'max_features': 'log2'}. Best is trial 84 with value: 0.4358038399164713.
[I 2026-05-23 09:34:23,932] Trial 94 finished with value: 0.4361624300532619 and parameters: {'n_estimators': 212, 'max_depth': 15, 'max_features': 'log2'}. Best is trial 84 with value: 0.4358038399164713.
[I 2026-05-23 09:34:25,251] Trial 95 finished with value: 0.441840314952586 and parameters: {'n_estimators': 212, 'max_depth': 14, 'max_features': 'log2'}. Best is trial 84 with value: 0.4358038399164713.
[I 2026-05-23 09:34:26,647] Trial 96 finished with value: 0.43590365178942203 and parameters: {'n_estimators': 195, 'max_depth': 15, 'max_features': 'log2'}. Best is trial 84 with value: 0.4358038399164713.

Tuning LGBM for CC50 (Test-benchmarked)...

[I 2026-05-23 09:35:30,498] Trial 0 finished with value: 0.4405310415761464 and parameters: {'n_estimators': 296, 'learning_rate': 0.022288142476887693, 'num_leaves': 26}. Best is trial 0 with value: 0.4405310415761464.
[I 2026-05-23 09:35:31,336] Trial 1 finished with value: 0.44552533252578475 and parameters: {'n_estimators': 164, 'learning_rate': 0.031135511833347635, 'num_leaves': 34}. Best is trial 0 with value: 0.4405310415761464.
[I 2026-05-23 09:35:31,890] Trial 2 finished with value: 0.44736032069693943 and parameters: {'n_estimators': 268, 'learning_rate': 0.07285173599254513, 'num_leaves': 9}. Best is trial 0 with value: 0.4405310415761464.
[I 2026-05-23 09:35:32,362] Trial 3 finished with value: 0.4539095383073938 and parameters: {'n_estimators': 108, 'learning_rate': 0.06558521647868726, 'num_leaves': 17}. Best is trial 0 with value: 0.4405310415761464.
[I 2026-05-23 09:35:34,215] Trial 4 finished with value: 0.43272581163373547 and parameters: {'n_estimators': 335, 'learning_rate': 0.03521495191656553, 'num_leaves': 43}. Best is trial 4 with value: 0.43272581163373547.
[I 2026-05-23 09:35:35,610] Trial 5 finished with value: 0.44642920777602413 and parameters: {'n_estimators': 276, 'learning_rate': 0.017509998073160775, 'num_leaves': 41}. Best is trial 4 with value: 0.43272581163373547.
[I 2026-05-23 09:35:35,739] Trial 6 finished with value: 0.6898884839308443 and parameters: {'n_estimators': 200, 'learning_rate': 0.005950447062659819, 'num_leaves': 2}. Best is trial 4 with value: 0.43272581163373547.
[I 2026-05-23 09:35:37,170] Trial 7 finished with value: 0.4360820137926973 and parameters: {'n_estimators': 236, 'learning_rate': 0.035977714315176566, 'num_leaves': 44}. Best is trial 4 with value: 0.43272581163373547.
[I 2026-05-23 09:35:38,511] Trial 8 finished with value: 0.4444396388368095 and parameters: {'n_estimators': 262, 'learning_rate': 0.021093012277552052, 'num_leaves': 56}. Best is trial 4 with value: 0.43272581163373547.
[I 2026-05-23 09:35:38,700] Trial 9 finished with value: 0.5595499406669431 and parameters: {'n_estimators': 38, 'learning_rate': 0.02577088808089516, 'num_leaves': 21}. Best is trial 4 with value: 0.43272581163373547.
[I 2026-05-23 09:35:41,237] Trial 10 finished with value: 0.44994029955345405 and parameters: {'n_estimators': 397, 'learning_rate': 0.010573920211092065, 'num_leaves': 60}. Best is trial 4 with value: 0.43272581163373547.
[I 2026-05-23 09:35:43,926] Trial 11 finished with value: 0.4305299661988525 and parameters: {'n_estimators': 370, 'learning_rate': 0.0505896112287866, 'num_leaves': 46}. Best is trial 11 with value: 0.4305299661988525.
[I 2026-05-23 09:35:46,483] Trial 12 finished with value: 0.43135019032330235 and parameters: {'n_estimators': 394, 'learning_rate': 0.04439507267677814, 'num_leaves': 48}. Best is trial 11 with value: 0.4305299661988525.
[I 2026-05-23 09:35:48,810] Trial 13 finished with value: 0.433940229881543 and parameters: {'n_estimators': 394, 'learning_rate': 0.09738513252049764, 'num_leaves': 51}. Best is trial 11 with value: 0.4305299661988525.
[I 2026-05-23 09:35:50,667] Trial 14 finished with value: 0.4305475499397711 and parameters: {'n_estimators': 343, 'learning_rate': 0.04746607418557928, 'num_leaves': 34}. Best is trial 11 with value: 0.4305299661988525.
[I 2026-05-23 09:35:52,501] Trial 15 finished with value: 0.4341498140180289 and parameters: {'n_estimators': 332, 'learning_rate': 0.061996831118888936, 'num_leaves': 35}. Best is trial 11 with value: 0.4305299661988525.
[I 2026-05-23 09:35:55,817] Trial 16 finished with value: 0.43497929943703734 and parameters: {'n_estimators': 339, 'learning_rate': 0.04946553528866978, 'num_leaves': 37}. Best is trial 11 with value: 0.4305299661988525.
[I 2026-05-23 09:35:57,607] Trial 17 finished with value: 0.43592718961281 and parameters: {'n_estimators': 345, 'learning_rate': 0.09854773319600603, 'num_leaves': 27}. Best is trial 11 with value: 0.4305299661988525.
[I 2026-05-23 09:35:58,386] Trial 18 finished with value: 0.486617209809478 and parameters: {'n_estimators': 152, 'learning_rate': 0.01357720184213937, 'num_leaves': 51}. Best is trial 11 with value: 0.4305299661988525.
[I 2026-05-23 09:35:59,955] Trial 19 finished with value: 0.4313140882000981 and parameters: {'n_estimators': 296, 'learning_rate': 0.05138270758607987, 'num_leaves': 29}. Best is trial 11 with value: 0.4305299661988525.
[I 2026-05-23 09:36:01,281] Trial 20 finished with value: 0.487001150319776 and parameters: {'n_estimators': 356, 'learning_rate': 0.007720516296247223, 'num_leaves': 18}. Best is trial 11 with value: 0.4305299661988525.
[I 2026-05-23 09:36:02,895] Trial 21 finished with value: 0.4309184958859038 and parameters: {'n_estimators': 293, 'learning_rate': 0.0503413773018767, 'num_leaves': 29}. Best is trial 11 with value: 0.4305299661988525.
[I 2026-05-23 09:36:04,901] Trial 22 finished with value: 0.43013587389762253 and parameters: {'n_estimators': 366, 'learning_rate': 0.040952946057398916, 'num_leaves': 39}. Best is trial 22 with value: 0.43013587389762253.
[I 2026-05-23 09:36:07,949] Trial 23 finished with value: 0.43264118431488374 and parameters: {'n_estimators': 369, 'learning_rate': 0.03972581680659195, 'num_leaves': 41}. Best is trial 22 with value: 0.43013587389762253.
[I 2026-05-23 09:36:09,770] Trial 24 finished with value: 0.43704717428222517 and parameters: {'n_estimators': 325, 'learning_rate': 0.02876982148525544, 'num_leaves': 38}. Best is trial 22 with value: 0.43013587389762253.
[I 2026-05-23 09:36:11,240] Trial 25 finished with value: 0.4319027130024323 and parameters: {'n_estimators': 229, 'learning_rate': 0.05603342473916802, 'num_leaves': 49}. Best is trial 22 with value: 0.43013587389762253.
[I 2026-05-23 09:36:13,343] Trial 26 finished with value: 0.43252454725596534 and parameters: {'n_estimators': 369, 'learning_rate': 0.07756851206079486, 'num_leaves': 33}. Best is trial 22 with value: 0.43013587389762253.
[I 2026-05-23 09:36:14,976] Trial 27 finished with value: 0.4331702417300157 and parameters: {'n_estimators': 306, 'learning_rate': 0.041135871151999556, 'num_leaves': 45}. Best is trial 22 with value: 0.43013587389762253.
[I 2026-05-23 09:36:15,093] Trial 28 finished with value: 0.527866289210265 and parameters: {'n_estimators': 16, 'learning_rate': 0.07947742075918825, 'num_leaves': 23}. Best is trial 22 with value: 0.43013587389762253.
[I 2026-05-23 09:36:17,051] Trial 29 finished with value: 0.43533817430538096 and parameters: {'n_estimators': 313, 'learning_rate': 0.022346154127727173, 'num_leaves': 55}. Best is trial 22 with value: 0.43013587389762253.
[I 2026-05-23 09:36:20,240] Trial 30 finished with value: 0.4308408577615976 and parameters: {'n_estimators': 372, 'learning_rate': 0.030818581490725593, 'num_leaves': 39}. Best is trial 22 with value: 0.43013587389762253.
[I 2026-05-23 09:36:22,445] Trial 31 finished with value: 0.4356891393931248 and parameters: {'n_estimators': 366, 'learning_rate': 0.030970172523113654, 'num_leaves': 39}. Best is trial 22 with value: 0.43013587389762253.
[I 2026-05-23 09:36:24,428] Trial 32 finished with value: 0.4397336411906916 and parameters: {'n_estimators': 377, 'learning_rate': 0.01721536089692405, 'num_leaves': 31}. Best is trial 22 with value: 0.43013587389762253.
[I 2026-05-23 09:36:26,315] Trial 33 finished with value: 0.4337654517695676 and parameters: {'n_estimators': 354, 'learning_rate': 0.02776401421895951, 'num_leaves': 46}. Best is trial 22 with value: 0.43013587389762253.
[I 2026-05-23 09:36:28,412] Trial 34 finished with value: 0.4354115590579795 and parameters: {'n_estimators': 384, 'learning_rate': 0.0376609266024169, 'num_leaves': 33}. Best is trial 22 with value: 0.43013587389762253.
[I 2026-05-23 09:36:28,992] Trial 35 finished with value: 0.4423717050005056 and parameters: {'n_estimators': 105, 'learning_rate': 0.06288298532265779, 'num_leaves': 35}. Best is trial 22 with value: 0.43013587389762253.
[I 2026-05-23 09:36:30,427] Trial 36 finished with value: 0.43660542366051747 and parameters: {'n_estimators': 270, 'learning_rate': 0.03270932402104154, 'num_leaves': 41}. Best is trial 22 with value: 0.43013587389762253.
[I 2026-05-23 09:36:32,609] Trial 37 finished with value: 0.43488294938726507 and parameters: {'n_estimators': 323, 'learning_rate': 0.045134035747863094, 'num_leaves': 24}. Best is trial 22 with value: 0.43013587389762253.
[I 2026-05-23 09:36:33,984] Trial 38 finished with value: 0.45629154594760474 and parameters: {'n_estimators': 184, 'learning_rate': 0.019277208927272187, 'num_leaves': 42}. Best is trial 22 with value: 0.43013587389762253.
[I 2026-05-23 09:36:34,740] Trial 39 finished with value: 0.4605723001711671 and parameters: {'n_estimators': 244, 'learning_rate': 0.026574995420332276, 'num_leaves': 14}. Best is trial 22 with value: 0.43013587389762253.
[I 2026-05-23 09:36:36,301] Trial 40 finished with value: 0.43572478346134097 and parameters: {'n_estimators': 289, 'learning_rate': 0.0681411303987608, 'num_leaves': 37}. Best is trial 22 with value: 0.43013587389762253.
[I 2026-05-23 09:36:38,189] Trial 41 finished with value: 0.43463493370034567 and parameters: {'n_estimators': 349, 'learning_rate': 0.05423090107181268, 'num_leaves': 30}. Best is trial 22 with value: 0.43013587389762253.
[I 2026-05-23 09:36:39,607] Trial 42 finished with value: 0.435330402881159 and parameters: {'n_estimators': 286, 'learning_rate': 0.03414196459553583, 'num_leaves': 26}. Best is trial 22 with value: 0.43013587389762253.
[I 2026-05-23 09:36:41,559] Trial 43 finished with value: 0.43282562302169725 and parameters: {'n_estimators': 311, 'learning_rate': 0.04682608767816208, 'num_leaves': 39}. Best is trial 22 with value: 0.43013587389762253.
[I 2026-05-23 09:36:43,554] Trial 44 finished with value: 0.43271986108703564 and parameters: {'n_estimators': 377, 'learning_rate': 0.05681028586712437, 'num_leaves': 28}. Best is trial 22 with value: 0.43013587389762253.
[I 2026-05-23 09:36:46,420] Trial 45 finished with value: 0.43252212750196184 and parameters: {'n_estimators': 327, 'learning_rate': 0.0412226897464043, 'num_leaves': 32}. Best is trial 22 with value: 0.43013587389762253.
[I 2026-05-23 09:36:46,632] Trial 46 finished with value: 0.5909468927126496 and parameters: {'n_estimators': 395, 'learning_rate': 0.023940658123930453, 'num_leaves': 2}. Best is trial 22 with value: 0.43013587389762253.
[I 2026-05-23 09:36:48,120] Trial 47 finished with value: 0.4341052056794651 and parameters: {'n_estimators': 254, 'learning_rate': 0.08011075842960173, 'num_leaves': 44}. Best is trial 22 with value: 0.43013587389762253.
[I 2026-05-23 09:36:49,994] Trial 48 finished with value: 0.43537093059053644 and parameters: {'n_estimators': 343, 'learning_rate': 0.03703092835007475, 'num_leaves': 48}. Best is trial 22 with value: 0.43013587389762253.
[I 2026-05-23 09:36:52,300] Trial 49 finished with value: 0.43239838626219984 and parameters: {'n_estimators': 356, 'learning_rate': 0.0491651956937918, 'num_leaves': 35}. Best is trial 22 with value: 0.43013587389762253.
[I 2026-05-23 09:36:54,474] Trial 50 finished with value: 0.4325620628783712 and parameters: {'n_estimators': 398, 'learning_rate': 0.03126133369779395, 'num_leaves': 52}. Best is trial 22 with value: 0.43013587389762253.
[I 2026-05-23 09:36:56,098] Trial 51 finished with value: 0.43595133722460694 and parameters: {'n_estimators': 295, 'learning_rate': 0.05136043035989162, 'num_leaves': 30}. Best is trial 22 with value: 0.43013587389762253.
[I 2026-05-23 09:36:57,516] Trial 52 finished with value: 0.4450663947320599 and parameters: {'n_estimators': 222, 'learning_rate': 0.043873500601930036, 'num_leaves': 20}. Best is trial 22 with value: 0.43013587389762253.
[I 2026-05-23 09:36:59,769] Trial 53 finished with value: 0.4323702850188603 and parameters: {'n_estimators': 303, 'learning_rate': 0.05742724271412044, 'num_leaves': 28}. Best is trial 22 with value: 0.43013587389762253.
[I 2026-05-23 09:37:01,696] Trial 54 finished with value: 0.4325304425983405 and parameters: {'n_estimators': 329, 'learning_rate': 0.07208721518483283, 'num_leaves': 36}. Best is trial 22 with value: 0.43013587389762253.
[I 2026-05-23 09:37:03,336] Trial 55 finished with value: 0.4992330170092414 and parameters: {'n_estimators': 361, 'learning_rate': 0.005082987443214279, 'num_leaves': 25}. Best is trial 22 with value: 0.43013587389762253.
[I 2026-05-23 09:37:04,958] Trial 56 finished with value: 0.4348443791047613 and parameters: {'n_estimators': 275, 'learning_rate': 0.0864745826675241, 'num_leaves': 40}. Best is trial 22 with value: 0.43013587389762253.
[I 2026-05-23 09:37:07,123] Trial 57 finished with value: 0.4303200423787623 and parameters: {'n_estimators': 382, 'learning_rate': 0.06336304273848127, 'num_leaves': 43}. Best is trial 22 with value: 0.43013587389762253.
[I 2026-05-23 09:37:09,042] Trial 58 finished with value: 0.4340747889240483 and parameters: {'n_estimators': 340, 'learning_rate': 0.06365828449194347, 'num_leaves': 46}. Best is trial 22 with value: 0.43013587389762253.
[I 2026-05-23 09:37:12,680] Trial 59 finished with value: 0.43153533550020323 and parameters: {'n_estimators': 383, 'learning_rate': 0.042142936210448734, 'num_leaves': 43}. Best is trial 22 with value: 0.43013587389762253.
[I 2026-05-23 09:37:14,823] Trial 60 finished with value: 0.4342909948697433 and parameters: {'n_estimators': 381, 'learning_rate': 0.06002986104544582, 'num_leaves': 55}. Best is trial 22 with value: 0.43013587389762253.
[I 2026-05-23 09:37:16,889] Trial 61 finished with value: 0.4327506311179596 and parameters: {'n_estimators': 366, 'learning_rate': 0.05211891609822227, 'num_leaves': 38}. Best is trial 22 with value: 0.43013587389762253.
[I 2026-05-23 09:37:18,663] Trial 62 finished with value: 0.4352275130308329 and parameters: {'n_estimators': 320, 'learning_rate': 0.03878768812775558, 'num_leaves': 34}. Best is trial 22 with value: 0.43013587389762253.
[I 2026-05-23 09:37:20,594] Trial 63 finished with value: 0.433055726495384 and parameters: {'n_estimators': 350, 'learning_rate': 0.04857515362600248, 'num_leaves': 29}. Best is trial 22 with value: 0.43013587389762253.
[I 2026-05-23 09:37:23,986] Trial 64 finished with value: 0.4313863280281578 and parameters: {'n_estimators': 372, 'learning_rate': 0.06824284393021178, 'num_leaves': 32}. Best is trial 22 with value: 0.43013587389762253.
[I 2026-05-23 09:37:24,732] Trial 65 finished with value: 0.4632610280739143 and parameters: {'n_estimators': 95, 'learning_rate': 0.03477183016334172, 'num_leaves': 48}. Best is trial 22 with value: 0.43013587389762253.
[I 2026-05-23 09:37:26,895] Trial 66 finished with value: 0.433323467962764 and parameters: {'n_estimators': 336, 'learning_rate': 0.03007180953504309, 'num_leaves': 43}. Best is trial 22 with value: 0.43013587389762253.
[I 2026-05-23 09:37:29,062] Trial 67 finished with value: 0.43231193611414176 and parameters: {'n_estimators': 388, 'learning_rate': 0.045657538092322696, 'num_leaves': 40}. Best is trial 22 with value: 0.43013587389762253.
[I 2026-05-23 09:37:29,801] Trial 68 finished with value: 0.4388446084095 and parameters: {'n_estimators': 129, 'learning_rate': 0.08703202511284448, 'num_leaves': 37}. Best is trial 22 with value: 0.43013587389762253.
[I 2026-05-23 09:37:31,468] Trial 69 finished with value: 0.43654321349559044 and parameters: {'n_estimators': 258, 'learning_rate': 0.05159383809675917, 'num_leaves': 46}. Best is trial 22 with value: 0.43013587389762253.
[I 2026-05-23 09:37:32,540] Trial 70 finished with value: 0.4470795711612535 and parameters: {'n_estimators': 202, 'learning_rate': 0.024663436805733168, 'num_leaves': 34}. Best is trial 22 with value: 0.43013587389762253.
[I 2026-05-23 09:37:34,992] Trial 71 finished with value: 0.4328470406680459 and parameters: {'n_estimators': 399, 'learning_rate': 0.042978454362071795, 'num_leaves': 52}. Best is trial 22 with value: 0.43013587389762253.
[I 2026-05-23 09:37:37,857] Trial 72 finished with value: 0.4340446477521688 and parameters: {'n_estimators': 361, 'learning_rate': 0.038478685392921604, 'num_leaves': 50}. Best is trial 22 with value: 0.43013587389762253.
[I 2026-05-23 09:37:39,949] Trial 73 finished with value: 0.4333616694152044 and parameters: {'n_estimators': 374, 'learning_rate': 0.059727308092912254, 'num_leaves': 47}. Best is trial 22 with value: 0.43013587389762253.
[I 2026-05-23 09:37:42,096] Trial 74 finished with value: 0.4330124214148575 and parameters: {'n_estimators': 389, 'learning_rate': 0.05418028039902806, 'num_leaves': 41}. Best is trial 22 with value: 0.43013587389762253.
[I 2026-05-23 09:37:43,592] Trial 75 finished with value: 0.4710419422644659 and parameters: {'n_estimators': 350, 'learning_rate': 0.009193001045603718, 'num_leaves': 22}. Best is trial 22 with value: 0.43013587389762253.
[I 2026-05-23 09:37:45,611] Trial 76 finished with value: 0.4361670978514385 and parameters: {'n_estimators': 368, 'learning_rate': 0.03494407869245849, 'num_leaves': 59}. Best is trial 22 with value: 0.43013587389762253.
[I 2026-05-23 09:37:47,424] Trial 77 finished with value: 0.43064707555003184 and parameters: {'n_estimators': 319, 'learning_rate': 0.047019592128352945, 'num_leaves': 44}. Best is trial 22 with value: 0.43013587389762253.
[I 2026-05-23 09:37:50,045] Trial 78 finished with value: 0.43309485500755857 and parameters: {'n_estimators': 282, 'learning_rate': 0.06601355045708761, 'num_leaves': 43}. Best is trial 22 with value: 0.43013587389762253.
[I 2026-05-23 09:37:52,093] Trial 79 finished with value: 0.4330663344015127 and parameters: {'n_estimators': 317, 'learning_rate': 0.04664834223025209, 'num_leaves': 45}. Best is trial 22 with value: 0.43013587389762253.
[I 2026-05-23 09:37:53,799] Trial 80 finished with value: 0.43089726824726654 and parameters: {'n_estimators': 304, 'learning_rate': 0.0706986291435624, 'num_leaves': 39}. Best is trial 22 with value: 0.43013587389762253.
[I 2026-05-23 09:37:55,535] Trial 81 finished with value: 0.43382617204176854 and parameters: {'n_estimators': 303, 'learning_rate': 0.056790739412763816, 'num_leaves': 39}. Best is trial 22 with value: 0.43013587389762253.
[I 2026-05-23 09:37:57,773] Trial 82 finished with value: 0.4270240857996601 and parameters: {'n_estimators': 331, 'learning_rate': 0.07439435321346234, 'num_leaves': 42}. Best is trial 82 with value: 0.4270240857996601.
[I 2026-05-23 09:37:59,600] Trial 83 finished with value: 0.4318133835291892 and parameters: {'n_estimators': 330, 'learning_rate': 0.07076246667642419, 'num_leaves': 42}. Best is trial 82 with value: 0.4270240857996601.
[I 2026-05-23 09:38:02,600] Trial 84 finished with value: 0.4308682654451602 and parameters: {'n_estimators': 339, 'learning_rate': 0.08805603923632818, 'num_leaves': 37}. Best is trial 82 with value: 0.4270240857996601.
[I 2026-05-23 09:38:04,608] Trial 85 finished with value: 0.4329381660003613 and parameters: {'n_estimators': 340, 'learning_rate': 0.08976452947683604, 'num_leaves': 37}. Best is trial 82 with value: 0.4270240857996601.
[I 2026-05-23 09:38:06,615] Trial 86 finished with value: 0.4335870800059143 and parameters: {'n_estimators': 349, 'learning_rate': 0.07711144397037258, 'num_leaves': 44}. Best is trial 82 with value: 0.4270240857996601.
[I 2026-05-23 09:38:08,728] Trial 87 finished with value: 0.43363430448514745 and parameters: {'n_estimators': 359, 'learning_rate': 0.08180436472100254, 'num_leaves': 40}. Best is trial 82 with value: 0.4270240857996601.
[I 2026-05-23 09:38:10,516] Trial 88 finished with value: 0.4316500753474928 and parameters: {'n_estimators': 316, 'learning_rate': 0.09229007419906639, 'num_leaves': 36}. Best is trial 82 with value: 0.4270240857996601.
[I 2026-05-23 09:38:12,721] Trial 89 finished with value: 0.4326528117845626 and parameters: {'n_estimators': 335, 'learning_rate': 0.062066312689091824, 'num_leaves': 38}. Best is trial 82 with value: 0.4270240857996601.

In [ ]:
best_gbr_cc

{'n_estimators': 338,
 'learning_rate': 0.07917569954940945,
 'max_depth': 7,
 'subsample': 0.8950529393998701}

In [ ]:
best_rf_cc

{'n_estimators': 239, 'max_depth': 15, 'max_features': 'log2'}

In [ ]:
best_lgbm_cc

{'n_estimators': 331, 'learning_rate': 0.07439435321346234, 'num_leaves': 42}

In [ ]:
best_lgbm_cc={'n_estimators': 331, 'learning_rate': 0.07439435321346234, 'num_leaves': 42}
best_rf_cc={'n_estimators': 239, 'max_depth': 15, 'max_features': 'log2'}
best_gbr_cc={'n_estimators': 338,
 'learning_rate': 0.07917569954940945,
 'max_depth': 7,
 'subsample': 0.8950529393998701}

In [ ]:
# Сравнение оптимизированных моделей на CC50
cc_results = []
models_cc = {
    "GBR": GradientBoostingRegressor(**best_gbr_cc, random_state=42),
    "RF": RandomForestRegressor(**best_rf_cc, random_state=42),
    "LGBM": lgb.LGBMRegressor(**best_lgbm_cc, random_state=42, verbosity=-1)
}

for name, model in models_cc.items():
    model.fit(X_train_cc, y_train_cc)
    tr_p= model.predict(X_train_cc)
    te_p = model.predict(X_test_cc)
    cc_results.append({
        "Model": name,
        "Train RMSE": np.sqrt(mean_squared_error(y_train_cc, tr_p)),
        "Test RMSE": np.sqrt(mean_squared_error(y_test_cc, te_p)),
        "Test R2": r2_score(y_test_cc, te_p)
    })

display(pd.DataFrame(cc_results))

  Model  Train RMSE  Test RMSE   Test R2
0   GBR    0.287550   0.549681  0.487992
1    RF    0.328339   0.542752  0.500819
2  LGBM    0.286731   0.567318  0.454610

удалосm немного улучшить метрику качетсва на тесте

### CC50: Оценка на данных без выбросов
Теперь проверим, улучшится ли предсказание CC50, если мы уберем выбросы (те же 49 молекул, что и для IC50).

In [ ]:
# Фильтруем те же данные для CC50
df_cc_f = df_cc[df_cc['is_outlier'] == 1].copy()
X_cc_f = df_cc_f[relevant_features_cc]
y_cc_f = -np.log10(df_cc_f[target_cc50])

X_tr_cc_f, X_te_cc_f, y_tr_cc_f, y_te_cc_f = train_test_split(X_cc_f, y_cc_f, test_size=0.2, random_state=42)

# Проверяем лучшую модель (например, RF) на чистых данных
final_model_cc = RandomForestRegressor(**best_rf_cc, random_state=42)
final_model_cc.fit(X_tr_cc_f, y_tr_cc_f)

f_preds = final_model_cc.predict(X_te_cc_f)
print(f"CC50 Results (Outliers Removed):")
print(f"RMSE: {np.sqrt(mean_squared_error(y_te_cc_f, f_preds)):.4f}")
print(f"R2:   {r2_score(y_te_cc_f, f_preds):.4f}")

CC50 Results (Outliers Removed):
RMSE: 0.5641
R2:   0.4066

интерсно что в данной задаче удаление выбросов не улучшает модель возможно предельные значения имеют взаимосвясь с cc50